[package]
name = "uucore"
version = "0.0.1"
authors = []

[dependencies]
libc = { git = "https://github.com/rust-lang/libc.git" }
getopts = "*"
data-encoding = "^1.1"

[lib]
path = "lib.rs"
name = "uucore"
