[package]
name = "uucore"
version = "0.0.1"
authors = []

[dependencies]
libc = { git = "https://github.com/rust-lang/libc.git" }
getopts = "*"
time = { version = "*", optional = true }
data-encoding = { version = "^1.1", optional = true }

[features]
fs = []
utf8 = []
encoding = ["data-encoding"]
parse_time = []
utmpx = ["time"]
c_types = []
process = []
signals = []
wide = []
default = ["fs", "utf8", "encoding", "parse_time", "utmpx", "c_types", "process", "signals", "wide"]

[lib]
path = "lib.rs"
name = "uucore"
