[package]
name = "uucore"
version = "0.0.1"
authors = []

[dependencies]
getopts = "0.2.14"
time = { version = "0.1.38", optional = true }
data-encoding = { version = "^1.1", optional = true }
libc = { version = "0.2.34", optional = true }

[target.'cfg(target_os = "redox")'.dependencies]
termion = "1.5"

[features]
fs = ["libc"]
utf8 = []
encoding = ["data-encoding"]
parse_time = []
mode = ["libc"]
utmpx = ["time", "libc"]
process = ["libc"]
signals = []
entries = ["libc"]
wide = []
default = []

[lib]
path = "lib.rs"
name = "uucore"
